// RootLayout.js
import React from 'react';
import { ThemeProvider } from '../ThemeContext';
import './globals.css'; // Import global styles
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
};

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default RootLayout;
